version: "2.1"
services:
  radarr:
    build: .
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/radarr/radarr/data:/config
      - /home/pi/radarr/radarr/movies:/movies
      - /home/pi/radarr/deluge/downloads:/downloads
    restart: unless-stopped
    ports: 
      - 7878:7878

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    depends_on:
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/pi/radarr/deluge/config:/config
      - /home/pi/radarr/deluge/downloads:/downloads
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    depends_on:
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/pi/radarr/jackett/config:/config
      - /home/pi/radarr/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/pi/radarr/plex/config:/config
      - /home/pi/radarr/radarr/movies:/movies
    restart: unless-stopped

